version: '3.8'
services:

  # Serviço MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clientes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  # Serviço do backend Spring Boot (Kotlin)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clientes-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clientes
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
